### PR TITLE
Metadata Infrastructure

### PR DESCRIPTION
**Pull request by tbreimer14**
This closes issue #109

### CODE REVIEW

**Review by CalebLItalien — COMMENTED** [review]
I like this idea, and I think you're on the right track. You're definitely representing the data we want to represent in this issue. My problem with this implementation is that it wraps the instances with the metadata enum, which might be more headache than its worth. I think instead, what if we created a standalone Metadata enum, that holds information about the target instance, then gets added as a field to the target object type. For example, we could define a Token metadata variant:

```
enum Module {
     Token {
         field one about tokens
         field two about tokens
         etc, but no actual token here
      }
      ...
  }
  
Then when we lex, we add an instance of Metadata::Token to each Token we create. We would need to modify our lexing/token infrastructure to do this, but I think this is a more extensible approach. We can then just have a pointer to the Metadata::Token instance inside each token, reducing our overhead.

**Comment by tbreimer14** [comment]
That makes total sense, and is what I was thinking too, not sure why I decided to have a type field as well. What exactly do you mean by adding an instance of Metadata::Token to each Token? Should each Token variant have a Metadata field?

**Comment by CalebLItalien** [comment]
Yes, I think each Token variant will need a new field for hosting its metadata. You don’t need to actually that for this issue, this issue is just focused on the infrastructure for that.

**Review by Dalyj24 — APPROVED** [review]
I like this solution!

**Pull request merged**
